import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// Universal Pantomime terms - perfect for acting out without speaking!
// Mix of Level 2 (Medium) and Level 3 (Hard)

const PANTOMIME_TERMS_DE = [
    // Level 2 - Medium (75 terms)
    { term: 'Zahnarzt', difficulty: 2, hint: 'Bohren im Mund' },
    { term: 'Dirigent', difficulty: 2, hint: 'Orchester leiten mit Taktstock' },
    { term: 'Surfer', difficulty: 2, hint: 'Auf Wellen reiten' },
    { term: 'Bogenschütze', difficulty: 2, hint: 'Pfeil und Bogen' },
    { term: 'Kellner', difficulty: 2, hint: 'Tablett tragen' },
    { term: 'Yoga', difficulty: 2, hint: 'Entspannende Übungen' },
    { term: 'Einbrecher', difficulty: 2, hint: 'Heimlich einsteigen' },
    { term: 'Boxer', difficulty: 2, hint: 'Mit Fäusten kämpfen' },
    { term: 'Friseur', difficulty: 2, hint: 'Haare schneiden' },
    { term: 'Angler', difficulty: 2, hint: 'Fische fangen' },
    { term: 'DJ', difficulty: 2, hint: 'Platten auflegen' },
    { term: 'Astronaut', difficulty: 2, hint: 'Im Weltraum schweben' },
    { term: 'Taucher', difficulty: 2, hint: 'Unter Wasser' },
    { term: 'Cowboy', difficulty: 2, hint: 'Wilder Westen' },
    { term: 'Pilot', difficulty: 2, hint: 'Flugzeug steuern' },
    { term: 'Schiedsrichter', difficulty: 2, hint: 'Gelbe/Rote Karte' },
    { term: 'Fotograf', difficulty: 2, hint: 'Bilder machen' },
    { term: 'Zauberer', difficulty: 2, hint: 'Tricks vorführen' },
    { term: 'Gärtner', difficulty: 2, hint: 'Blumen pflanzen' },
    { term: 'Maler', difficulty: 2, hint: 'Mit Pinsel' },
    { term: 'Bäcker', difficulty: 2, hint: 'Teig kneten' },
    { term: 'Schlagzeuger', difficulty: 2, hint: 'Drums spielen' },
    { term: 'Ballerina', difficulty: 2, hint: 'Elegant tanzen' },
    { term: 'Ninja', difficulty: 2, hint: 'Kampfkunst' },
    { term: 'Roboter', difficulty: 2, hint: 'Mechanische Bewegungen' },
    { term: 'Zombie', difficulty: 2, hint: 'Langsam, Arme vorne' },
    { term: 'Sumo-Ringer', difficulty: 2, hint: 'Japanischer Kampfsport' },
    { term: 'Cheerleader', difficulty: 2, hint: 'Mit Pompons' },
    { term: 'Ritter', difficulty: 2, hint: 'Mit Schwert und Schild' },
    { term: 'Pirat', difficulty: 2, hint: 'Augenklappe, Schiff' },
    { term: 'Clown', difficulty: 2, hint: 'Lustig, große Schuhe' },
    { term: 'Arzt', difficulty: 2, hint: 'Stethoskop' },
    { term: 'Masseur', difficulty: 2, hint: 'Rücken massieren' },
    { term: 'Golferin', difficulty: 2, hint: 'Ball schlagen' },
    { term: 'Tennisspieler', difficulty: 2, hint: 'Mit Schläger' },
    { term: 'Bodybuilder', difficulty: 2, hint: 'Muskeln zeigen' },
    { term: 'Skifahrer', difficulty: 2, hint: 'Bergab fahren' },
    { term: 'Eiskunstläuferin', difficulty: 2, hint: 'Pirouetten' },
    { term: 'Jäger', difficulty: 2, hint: 'Mit Gewehr' },
    { term: 'Koch', difficulty: 2, hint: 'In der Küche' },
    { term: 'Geigenspieler', difficulty: 2, hint: 'Streichinstrument' },
    { term: 'Trommler', difficulty: 2, hint: 'Auf Trommel schlagen' },
    { term: 'Rapper', difficulty: 2, hint: 'Hip-Hop Gesten' },
    { term: 'Rockstar', difficulty: 2, hint: 'Gitarre, Bühne' },
    { term: 'Model', difficulty: 2, hint: 'Auf Laufsteg' },
    { term: 'Feuerwehrmann', difficulty: 2, hint: 'Feuer löschen' },
    { term: 'Polizist', difficulty: 2, hint: 'Festnehmen' },
    { term: 'Soldat', difficulty: 2, hint: 'Marschieren' },
    { term: 'Schwangere', difficulty: 2, hint: 'Dicker Bauch' },
    { term: 'Baby', difficulty: 2, hint: 'Krabbeln, weinen' },
    { term: 'Gorilla', difficulty: 2, hint: 'Brust schlagen' },
    { term: 'Känguru', difficulty: 2, hint: 'Hüpfen' },
    { term: 'Schlange', difficulty: 2, hint: 'Am Boden schlängeln' },
    { term: 'Vogel', difficulty: 2, hint: 'Flügel schlagen' },
    { term: 'Hund', difficulty: 2, hint: 'Bellen, Schwanz wedeln' },
    { term: 'Katze', difficulty: 2, hint: 'Miauen, schnurren' },
    { term: 'Frosch', difficulty: 2, hint: 'Hüpfen, Zunge' },
    { term: 'Spinne', difficulty: 2, hint: 'Acht Beine' },
    { term: 'Schneemann', difficulty: 2, hint: 'Rund, kalt' },
    { term: 'Weihnachtsmann', difficulty: 2, hint: 'Ho ho ho' },
    { term: 'Frankenstein', difficulty: 2, hint: 'Monster' },
    { term: 'Dracula', difficulty: 2, hint: 'Vampir' },
    { term: 'Selfie machen', difficulty: 2, hint: 'Handy halten' },
    { term: 'Skateboard fahren', difficulty: 2, hint: 'Brett mit Rollen' },
    { term: 'Karate', difficulty: 2, hint: 'Kampfsport' },
    { term: 'Gewichtheben', difficulty: 2, hint: 'Schwere Hanteln' },
    { term: 'Tischtennis', difficulty: 2, hint: 'Kleiner Ball' },
    { term: 'Basketball', difficulty: 2, hint: 'Korb werfen' },
    { term: 'Dart werfen', difficulty: 2, hint: 'Auf Scheibe zielen' },
    { term: 'Billard', difficulty: 2, hint: 'Mit Queue' },
    { term: 'Trampolin', difficulty: 2, hint: 'Hüpfen' },
    { term: 'Schaukeln', difficulty: 2, hint: 'Vor und zurück' },
    { term: 'Rutschen', difficulty: 2, hint: 'Spielplatz' },
    { term: 'Klettern', difficulty: 2, hint: 'Nach oben' },
    { term: 'Jonglieren', difficulty: 2, hint: 'Bälle in der Luft' },

    // Level 3 - Hard (75 terms)
    { term: 'Bauchredner', difficulty: 3, hint: 'Puppe spricht' },
    { term: 'Flaschenpost', difficulty: 3, hint: 'Nachricht im Meer' },
    { term: 'Seiltänzer', difficulty: 3, hint: 'Auf dünnem Seil' },
    { term: 'Schlafwandler', difficulty: 3, hint: 'Mit geschlossenen Augen' },
    { term: 'Zeitlupe', difficulty: 3, hint: 'Alles langsam' },
    { term: 'Stromschlag', difficulty: 3, hint: 'Elektrisiert' },
    { term: 'Fahrstuhl', difficulty: 3, hint: 'Hoch und runter' },
    { term: 'Staubsauger', difficulty: 3, hint: 'Haushaltsgerät' },
    { term: 'Waschmaschine', difficulty: 3, hint: 'Wäsche dreht sich' },
    { term: 'Spiegelei', difficulty: 3, hint: 'In der Pfanne' },
    { term: 'Popcorn', difficulty: 3, hint: 'Explodiert' },
    { term: 'Feuerwerk', difficulty: 3, hint: 'Am Himmel' },
    { term: 'Erdbeben', difficulty: 3, hint: 'Boden wackelt' },
    { term: 'Vulkanausbruch', difficulty: 3, hint: 'Lava spucken' },
    { term: 'Tornado', difficulty: 3, hint: 'Wirbelwind' },
    { term: 'Sonnenaufgang', difficulty: 3, hint: 'Langsam hoch' },
    { term: 'Mondlandung', difficulty: 3, hint: 'Schwerelosigkeit' },
    { term: 'Karussell', difficulty: 3, hint: 'Im Kreis drehen' },
    { term: 'Achterbahn', difficulty: 3, hint: 'Auf und ab' },
    { term: 'Riesenrad', difficulty: 3, hint: 'Langsam drehen' },
    { term: 'Drehtür', difficulty: 3, hint: 'Eingang/Ausgang' },
    { term: 'Rolltreppe', difficulty: 3, hint: 'Bewegende Treppe' },
    { term: 'Scheibenwischer', difficulty: 3, hint: 'Links rechts' },
    { term: 'Zapfsäule', difficulty: 3, hint: 'Tanken' },
    { term: 'Parkuhr', difficulty: 3, hint: 'Zeit läuft' },
    { term: 'Wecker', difficulty: 3, hint: 'Alarm' },
    { term: 'Sanduhr', difficulty: 3, hint: 'Sand rieselt' },
    { term: 'Kompass', difficulty: 3, hint: 'Richtung' },
    { term: 'Fernbedienung', difficulty: 3, hint: 'Zappen' },
    { term: 'Taschenrechner', difficulty: 3, hint: 'Rechnen' },
    { term: 'Kopfhörer', difficulty: 3, hint: 'Musik hören' },
    { term: 'Ladekabel', difficulty: 3, hint: 'Handy aufladen' },
    { term: 'WiFi', difficulty: 3, hint: 'Internet-Symbol' },
    { term: 'Emoji', difficulty: 3, hint: 'Gesichtsausdruck' },
    { term: 'Hashtag', difficulty: 3, hint: '# Symbol' },
    { term: 'Like', difficulty: 3, hint: 'Daumen hoch' },
    { term: 'Videocall', difficulty: 3, hint: 'Online Meeting' },
    { term: 'Download', difficulty: 3, hint: 'Herunterladen' },
    { term: 'Upload', difficulty: 3, hint: 'Hochladen' },
    { term: 'Screenshot', difficulty: 3, hint: 'Bildschirmfoto' },
    { term: 'Lautstärke', difficulty: 3, hint: 'Lauter/Leiser' },
    { term: 'Sprachassistent', difficulty: 3, hint: 'Hey Siri/Alexa' },
    { term: 'Drohne', difficulty: 3, hint: 'Fliegendes Ding' },
    { term: 'Selfie-Stick', difficulty: 3, hint: 'Langer Arm' },
    { term: 'Powerbank', difficulty: 3, hint: 'Mobiles Laden' },
    { term: 'Quietscheente', difficulty: 3, hint: 'Gummiente' },
    { term: 'Seifenblase', difficulty: 3, hint: 'Pusten' },
    { term: 'Papierflieger', difficulty: 3, hint: 'Gefaltet' },
    { term: 'Glückskeks', difficulty: 3, hint: 'Chinesisch' },
    { term: 'Zuckerwatte', difficulty: 3, hint: 'Jahrmarkt' },
    { term: 'Luftballon', difficulty: 3, hint: 'Aufblasen' },
    { term: 'Konfetti', difficulty: 3, hint: 'Party' },
    { term: 'Piñata', difficulty: 3, hint: 'Draufhauen' },
    { term: 'Hula-Hoop', difficulty: 3, hint: 'Ring um Hüfte' },
    { term: 'Jo-Jo', difficulty: 3, hint: 'Auf und ab' },
    { term: 'Zauberwürfel', difficulty: 3, hint: 'Rubiks Cube' },
    { term: 'Lego', difficulty: 3, hint: 'Bausteine' },
    { term: 'Puzzle', difficulty: 3, hint: 'Teile zusammen' },
    { term: 'Domino', difficulty: 3, hint: 'Steine fallen' },
    { term: 'Mikado', difficulty: 3, hint: 'Stäbchen' },
    { term: 'Memory', difficulty: 3, hint: 'Karten umdrehen' },
    { term: 'Verstecken spielen', difficulty: 3, hint: 'Suchen' },
    { term: 'Fangen spielen', difficulty: 3, hint: 'Weglaufen' },
    { term: 'Seilspringen', difficulty: 3, hint: 'Springen' },
    { term: 'Sackhüpfen', difficulty: 3, hint: 'Im Sack' },
    { term: 'Topfschlagen', difficulty: 3, hint: 'Geburtstagsparty' },
    { term: 'Eierlaufen', difficulty: 3, hint: 'Auf Löffel' },
    { term: 'Armdrücken', difficulty: 3, hint: 'Kraft messen' },
    { term: 'Daumendrücken', difficulty: 3, hint: 'Glück wünschen' },
    { term: 'Händeschütteln', difficulty: 3, hint: 'Begrüßung' },
    { term: 'High Five', difficulty: 3, hint: 'Hand oben' },
    { term: 'Fauststoß', difficulty: 3, hint: 'Fist Bump' },
    { term: 'Umarmung', difficulty: 3, hint: 'Drücken' },
    { term: 'Luftkuss', difficulty: 3, hint: 'Von weitem' },
    { term: 'Verbeugung', difficulty: 3, hint: 'Respekt zeigen' },
];

const PANTOMIME_TERMS_TR = [
    // Level 2 - Medium (75 terms)
    { term: 'Diş Hekimi', difficulty: 2, hint: 'Ağızda sondaj' },
    { term: 'Orkestra Şefi', difficulty: 2, hint: 'Batonla yönetmek' },
    { term: 'Sörfçü', difficulty: 2, hint: 'Dalgalarda' },
    { term: 'Okçu', difficulty: 2, hint: 'Ok ve yay' },
    { term: 'Garson', difficulty: 2, hint: 'Tepsi taşımak' },
    { term: 'Yoga Yapan', difficulty: 2, hint: 'Rahatlatıcı egzersiz' },
    { term: 'Hırsız', difficulty: 2, hint: 'Gizlice girmek' },
    { term: 'Boksör', difficulty: 2, hint: 'Yumruklaşmak' },
    { term: 'Kuaför', difficulty: 2, hint: 'Saç kesmek' },
    { term: 'Balıkçı', difficulty: 2, hint: 'Balık tutmak' },
    { term: 'DJ', difficulty: 2, hint: 'Plak çevirmek' },
    { term: 'Astronot', difficulty: 2, hint: 'Uzayda süzülmek' },
    { term: 'Dalgıç', difficulty: 2, hint: 'Su altında' },
    { term: 'Kovboy', difficulty: 2, hint: 'Vahşi Batı' },
    { term: 'Pilot', difficulty: 2, hint: 'Uçak kullanmak' },
    { term: 'Hakem', difficulty: 2, hint: 'Sarı/Kırmızı kart' },
    { term: 'Fotoğrafçı', difficulty: 2, hint: 'Resim çekmek' },
    { term: 'Sihirbaz', difficulty: 2, hint: 'Numara yapmak' },
    { term: 'Bahçıvan', difficulty: 2, hint: 'Çiçek ekmek' },
    { term: 'Ressam', difficulty: 2, hint: 'Fırçayla' },
    { term: 'Fırıncı', difficulty: 2, hint: 'Hamur yoğurmak' },
    { term: 'Baterist', difficulty: 2, hint: 'Davul çalmak' },
    { term: 'Balerin', difficulty: 2, hint: 'Zarif dans' },
    { term: 'Ninja', difficulty: 2, hint: 'Dövüş sanatı' },
    { term: 'Robot', difficulty: 2, hint: 'Mekanik hareketler' },
    { term: 'Zombi', difficulty: 2, hint: 'Yavaş, kollar önde' },
    { term: 'Sumo Güreşçisi', difficulty: 2, hint: 'Japon sporu' },
    { term: 'Amigo', difficulty: 2, hint: 'Ponponlarla' },
    { term: 'Şövalye', difficulty: 2, hint: 'Kılıç ve kalkan' },
    { term: 'Korsan', difficulty: 2, hint: 'Göz bandı, gemi' },
    { term: 'Palyaço', difficulty: 2, hint: 'Komik, büyük ayakkabı' },
    { term: 'Doktor', difficulty: 2, hint: 'Stetoskop' },
    { term: 'Masör', difficulty: 2, hint: 'Sırt masajı' },
    { term: 'Golfçü', difficulty: 2, hint: 'Top vurmak' },
    { term: 'Tenisçi', difficulty: 2, hint: 'Raketle' },
    { term: 'Vücut Geliştirici', difficulty: 2, hint: 'Kas göstermek' },
    { term: 'Kayakçı', difficulty: 2, hint: 'Dağdan inmek' },
    { term: 'Artistik Patenci', difficulty: 2, hint: 'Piruetler' },
    { term: 'Avcı', difficulty: 2, hint: 'Tüfekle' },
    { term: 'Aşçı', difficulty: 2, hint: 'Mutfakta' },
    { term: 'Kemancı', difficulty: 2, hint: 'Yaylı çalgı' },
    { term: 'Davulcu', difficulty: 2, hint: 'Davula vurmak' },
    { term: 'Rapçi', difficulty: 2, hint: 'Hip-Hop jestleri' },
    { term: 'Rock Yıldızı', difficulty: 2, hint: 'Gitar, sahne' },
    { term: 'Manken', difficulty: 2, hint: 'Podyumda' },
    { term: 'İtfaiyeci', difficulty: 2, hint: 'Yangın söndürmek' },
    { term: 'Polis', difficulty: 2, hint: 'Tutuklama' },
    { term: 'Asker', difficulty: 2, hint: 'Yürüyüş' },
    { term: 'Hamile', difficulty: 2, hint: 'Karnı şiş' },
    { term: 'Bebek', difficulty: 2, hint: 'Emeklemek, ağlamak' },
    { term: 'Goril', difficulty: 2, hint: 'Göğsüne vurmak' },
    { term: 'Kanguru', difficulty: 2, hint: 'Zıplamak' },
    { term: 'Yılan', difficulty: 2, hint: 'Yerde süzülmek' },
    { term: 'Kuş', difficulty: 2, hint: 'Kanat çırpmak' },
    { term: 'Köpek', difficulty: 2, hint: 'Havlamak, kuyruk sallamak' },
    { term: 'Kedi', difficulty: 2, hint: 'Miyavlamak, mırıldanmak' },
    { term: 'Kurbağa', difficulty: 2, hint: 'Zıplamak, dil' },
    { term: 'Örümcek', difficulty: 2, hint: 'Sekiz bacak' },
    { term: 'Kardan Adam', difficulty: 2, hint: 'Yuvarlak, soğuk' },
    { term: 'Noel Baba', difficulty: 2, hint: 'Ho ho ho' },
    { term: 'Frankenstein', difficulty: 2, hint: 'Canavar' },
    { term: 'Vampir', difficulty: 2, hint: 'Kan emici' },
    { term: 'Selfie Çekmek', difficulty: 2, hint: 'Telefon tutmak' },
    { term: 'Kaykay Sürmek', difficulty: 2, hint: 'Tekerlekli tahta' },
    { term: 'Karate', difficulty: 2, hint: 'Dövüş sanatı' },
    { term: 'Halter Kaldırmak', difficulty: 2, hint: 'Ağır dambıl' },
    { term: 'Masa Tenisi', difficulty: 2, hint: 'Küçük top' },
    { term: 'Basketbol', difficulty: 2, hint: 'Potaya atmak' },
    { term: 'Dart Atmak', difficulty: 2, hint: 'Hedefe nişan' },
    { term: 'Bilardo', difficulty: 2, hint: 'İstoçla' },
    { term: 'Trampolin', difficulty: 2, hint: 'Zıplamak' },
    { term: 'Salıncak', difficulty: 2, hint: 'İleri geri' },
    { term: 'Kaydırak', difficulty: 2, hint: 'Oyun parkı' },
    { term: 'Tırmanmak', difficulty: 2, hint: 'Yukarı' },
    { term: 'Hokkabazlık', difficulty: 2, hint: 'Topları havada' },

    // Level 3 - Hard (75 terms)
    { term: 'Karın Konuşan', difficulty: 3, hint: 'Kukla konuşur' },
    { term: 'Şişedeki Mesaj', difficulty: 3, hint: 'Denizde mesaj' },
    { term: 'İp Cambazı', difficulty: 3, hint: 'İnce ipte' },
    { term: 'Uyurgezer', difficulty: 3, hint: 'Kapalı gözle' },
    { term: 'Ağır Çekim', difficulty: 3, hint: 'Her şey yavaş' },
    { term: 'Elektrik Çarpması', difficulty: 3, hint: 'Elektriklenmiş' },
    { term: 'Asansör', difficulty: 3, hint: 'Yukarı aşağı' },
    { term: 'Elektrikli Süpürge', difficulty: 3, hint: 'Ev aleti' },
    { term: 'Çamaşır Makinesi', difficulty: 3, hint: 'Çamaşır dönüyor' },
    { term: 'Sahanda Yumurta', difficulty: 3, hint: 'Tavada' },
    { term: 'Patlamış Mısır', difficulty: 3, hint: 'Patlıyor' },
    { term: 'Havai Fişek', difficulty: 3, hint: 'Gökyüzünde' },
    { term: 'Deprem', difficulty: 3, hint: 'Yer sarsılıyor' },
    { term: 'Yanardağ Patlaması', difficulty: 3, hint: 'Lav püskürür' },
    { term: 'Kasırga', difficulty: 3, hint: 'Dönen rüzgar' },
    { term: 'Gün Doğumu', difficulty: 3, hint: 'Yavaşça yukarı' },
    { term: 'Aya İniş', difficulty: 3, hint: 'Yerçekimsizlik' },
    { term: 'Atlıkarınca', difficulty: 3, hint: 'Daire şeklinde' },
    { term: 'Lunapark Treni', difficulty: 3, hint: 'Yukarı aşağı' },
    { term: 'Dönme Dolap', difficulty: 3, hint: 'Yavaş dönüş' },
    { term: 'Döner Kapı', difficulty: 3, hint: 'Giriş/Çıkış' },
    { term: 'Yürüyen Merdiven', difficulty: 3, hint: 'Hareket eden' },
    { term: 'Silecek', difficulty: 3, hint: 'Sağa sola' },
    { term: 'Benzin Pompası', difficulty: 3, hint: 'Yakıt almak' },
    { term: 'Parkmetre', difficulty: 3, hint: 'Zaman işliyor' },
    { term: 'Çalar Saat', difficulty: 3, hint: 'Alarm' },
    { term: 'Kum Saati', difficulty: 3, hint: 'Kum akıyor' },
    { term: 'Pusula', difficulty: 3, hint: 'Yön' },
    { term: 'Uzaktan Kumanda', difficulty: 3, hint: 'Kanal değiştir' },
    { term: 'Hesap Makinesi', difficulty: 3, hint: 'Hesap yapmak' },
    { term: 'Kulaklık', difficulty: 3, hint: 'Müzik dinlemek' },
    { term: 'Şarj Kablosu', difficulty: 3, hint: 'Telefon şarj' },
    { term: 'WiFi', difficulty: 3, hint: 'İnternet sembolü' },
    { term: 'Emoji', difficulty: 3, hint: 'Yüz ifadesi' },
    { term: 'Hashtag', difficulty: 3, hint: '# Sembolü' },
    { term: 'Beğeni', difficulty: 3, hint: 'Başparmak yukarı' },
    { term: 'Görüntülü Arama', difficulty: 3, hint: 'Online toplantı' },
    { term: 'İndirme', difficulty: 3, hint: 'Dosya almak' },
    { term: 'Yükleme', difficulty: 3, hint: 'Dosya göndermek' },
    { term: 'Ekran Görüntüsü', difficulty: 3, hint: 'Ekran fotoğrafı' },
    { term: 'Ses Seviyesi', difficulty: 3, hint: 'Yükselt/Kıs' },
    { term: 'Sesli Asistan', difficulty: 3, hint: 'Hey Siri/Alexa' },
    { term: 'Drone', difficulty: 3, hint: 'Uçan şey' },
    { term: 'Selfie Çubuğu', difficulty: 3, hint: 'Uzun kol' },
    { term: 'Taşınabilir Şarj', difficulty: 3, hint: 'Mobil şarj' },
    { term: 'Lastik Ördek', difficulty: 3, hint: 'Banyo oyuncağı' },
    { term: 'Sabun Köpüğü', difficulty: 3, hint: 'Üflemek' },
    { term: 'Kağıt Uçak', difficulty: 3, hint: 'Katlanmış' },
    { term: 'Şans Kurabiyesi', difficulty: 3, hint: 'Çin tatlısı' },
    { term: 'Pamuk Şeker', difficulty: 3, hint: 'Lunaparkta' },
    { term: 'Balon', difficulty: 3, hint: 'Şişirmek' },
    { term: 'Konfeti', difficulty: 3, hint: 'Parti' },
    { term: 'Pinyata', difficulty: 3, hint: 'Sopaylaı vurmak' },
    { term: 'Hulahop', difficulty: 3, hint: 'Belde çember' },
    { term: 'Yoyo', difficulty: 3, hint: 'Yukarı aşağı' },
    { term: 'Zeka Küpü', difficulty: 3, hint: 'Rubik Küpü' },
    { term: 'Lego', difficulty: 3, hint: 'Yapı taşları' },
    { term: 'Yapboz', difficulty: 3, hint: 'Parçaları birleştir' },
    { term: 'Domino', difficulty: 3, hint: 'Taşlar düşer' },
    { term: 'Mikado', difficulty: 3, hint: 'Çubuklar' },
    { term: 'Hafıza Oyunu', difficulty: 3, hint: 'Kart çevirmek' },
    { term: 'Saklambaç', difficulty: 3, hint: 'Aramak' },
    { term: 'Yakalamaca', difficulty: 3, hint: 'Kaçmak' },
    { term: 'İp Atlamak', difficulty: 3, hint: 'Zıplamak' },
    { term: 'Çuval Yarışı', difficulty: 3, hint: 'Çuvalda' },
    { term: 'Körebe', difficulty: 3, hint: 'Göz kapalı' },
    { term: 'Yumurta Taşıma', difficulty: 3, hint: 'Kaşıkta' },
    { term: 'Bilek Güreşi', difficulty: 3, hint: 'Güç ölçmek' },
    { term: 'Parmak Bastırmak', difficulty: 3, hint: 'Şans dilemek' },
    { term: 'El Sıkışmak', difficulty: 3, hint: 'Selamlaşma' },
    { term: 'Çak', difficulty: 3, hint: 'El yukarıda' },
    { term: 'Yumruk Selamı', difficulty: 3, hint: 'Fist Bump' },
    { term: 'Sarılmak', difficulty: 3, hint: 'Kucaklamak' },
    { term: 'Öpücük Göndermek', difficulty: 3, hint: 'Uzaktan' },
    { term: 'Eğilmek', difficulty: 3, hint: 'Saygı göstermek' },
];

async function seedPantomimeTerms() {
    console.log('🎭 Seeding Pantomime terms...');

    // Delete existing pantomime_universal terms
    await prisma.bingoCard.deleteMany({
        where: { category: 'pantomime_universal' }
    });
    console.log('🗑️ Deleted existing pantomime_universal terms');

    let totalDE = 0;
    let totalTR = 0;

    // Insert German terms
    for (const term of PANTOMIME_TERMS_DE) {
        await prisma.bingoCard.create({
            data: {
                term: term.term,
                forbiddenWords: JSON.stringify([]), // No forbidden words for pantomime
                hint: term.hint,
                difficulty: term.difficulty,
                type: 'PANTOMIME',
                category: 'pantomime_universal',
                language: 'de'
            }
        });
        totalDE++;
    }
    console.log(`✅ Inserted ${totalDE} German pantomime terms`);

    // Insert Turkish terms
    for (const term of PANTOMIME_TERMS_TR) {
        await prisma.bingoCard.create({
            data: {
                term: term.term,
                forbiddenWords: JSON.stringify([]), // No forbidden words for pantomime
                hint: term.hint,
                difficulty: term.difficulty,
                type: 'PANTOMIME',
                category: 'pantomime_universal',
                language: 'tr'
            }
        });
        totalTR++;
    }
    console.log(`✅ Inserted ${totalTR} Turkish pantomime terms`);

    console.log(`🎉 Total: ${totalDE + totalTR} pantomime terms added!`);
}

seedPantomimeTerms()
    .catch(console.error)
    .finally(() => prisma.$disconnect());
